import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { getClasses } from "../api/getClasses";
import { Class } from "../types/Class";
import { Discipline } from "../types/Discipline";
import { Instructor } from "../types/Instructor";

interface FulfilledState {
  status: "fulfilled";
  classes: Class[];
  instructors: Instructor[];
  disciplines: Discipline[];
}

interface LoadingState {
  status: "loading";
}

interface FailedState {
  status: "failed";
  error: Partial<Error>;
}

export type ClassListState = LoadingState | FulfilledState | FailedState;

const initialState: ClassListState = {
  status: "loading",
} as ClassListState;

export const fetchClassList = createAsyncThunk(
  "classList/fetchClassList",
  async (classId: string) => {
    const response = await getClasses(classId);
    const instructors = response.data.instructors.map(
      (instructor): Instructor => {
        return {
          id: instructor.id,
          name: instructor.full_name,
          imageUrl: instructor.image_url,
          display: instructor.display,
        };
      }
    );
    const classes = response.data.classes.map((clazz): Class => {
      const instructor = instructors.find(
        (instructor) => instructor.id === clazz.instructor_id
      ) || {
        id: "0",
        name: "None",
        imageUrl: "",
        display: false,
      };

      return {
        ...clazz,
        name:
          clazz.name || `${clazz.duration / 60} min ${instructor.name} Class`,
        waitlistFull: clazz.waitlist_full,
        instructor,
      };
    });
    const disciplines = response.data.disciplines;
    return { classes, instructors, disciplines };
  }
);

export const classListSlice = createSlice({
  name: "classList",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchClassList.pending, (_) => {
        return { status: "loading" };
      })
      .addCase(fetchClassList.fulfilled, (_, action) => {
        return {
          status: "fulfilled",
          classes: action.payload.classes,
          instructors: action.payload.instructors,
          disciplines: action.payload.disciplines,
        };
      })
      .addCase(fetchClassList.rejected, (_, action) => {
        return { status: "failed", error: action.error };
      });
  },
});

export default classListSlice.reducer;
