name: Frontend — Build and Deploy

on:
  push:
    branches: [master]
    paths:
      - frontend/**
      - shared/**
      - package.json
      - pnpm-lock.yaml
  pull_request:
    branches: [master]
    paths:
      - frontend/**
      - shared/**
      - package.json
      - pnpm-lock.yaml
  workflow_dispatch:

env:
  BASE_URL: "/peloton-reservations/"
  VITE_FIREBASE_API_KEY: ${{ vars.VITE_FIREBASE_API_KEY }}

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build shared project
        run: pnpm run build
        working-directory: ./shared

      - name: Build project
        run: pnpm run build
        working-directory: ./frontend

      - name: Upload sourcemaps
        if: github.event_name != 'pull_request'
        run: pnpm run sentry-sourcemaps
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        working-directory: ./frontend

      - name: Upload artifacts
        if: github.event_name != 'pull_request'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./frontend/dist

  deploy:
    needs: build
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
